name: Detect Original Time Label

on:
  issues:
    types: [labeled]

jobs:
  run_on_label_assignment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test print
        run: |
            labels="${{ toJson(github.event.issue.labels) }}"
            json_labels=($(echo "$labels" | jq -c .))
            echo "All Labels: $json_labels"
            for label in "${json_labels[@]}"
              do 
                name=$(echo "$label" | jq -r '.name')
                echo "$name"
              done 
