name: Detect Original Time Label

on:
  issues:
    types: [labeled]

jobs:
  run_on_label_assignment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test print
        run: |
            labels="${{ toJson(github.event.issue.labels) }}"
            echo "All Labels: $labels"
            for label in labels; do
              echo "Assigned Label: $label"
            done
