name: Detect Original Time Label

on:
  issues:
    types: [labeled]

jobs:
  run_on_label_assignment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test print
        run: |
          json_labels=("${{ toJson(github.event.issue.labels) }}")
          for label in "${json_labels[@]}"; do
            echo "$label"
          done
