name: Detect Original Time Label

on:
  issues:
    types: [labeled]

jobs:
  run_on_label_assignment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test print
        if: contains(github.event.issue.labels.*.name, 'originaltime-')
        run: |
            for label in "${{ github.event.issue.labels.*.name }}"; do
            if [[ "$label" == "originaltime-"* ]]; then
              echo "Assigned Label: $label"
            fi
            done
