name: Detect Original Time Label

on:
  issues:
    types: [labeled]

jobs:
  run_on_label_assignment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test print
        run: |
            labels="${{ toJson(github.event.issue.labels) }}"
            echo "All Labels: $labels"
            echo $labels | jq -r '.[]' | while read label; do
              echo "Assigned Label: $label"
              if [[ "$label" == originaltime-* ]]; then
                echo "Label starting with 'originaltime-': $label"
              fi
            done
