name: Detect Original Time Label

on:
  issues:
    types: [labeled]

jobs:
  run_on_label_assignment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # TODO: fix the unsupported engine error
      # - name: Install
      #   run: npm install
      #   working-directory: ./roiScript

      - name: Send time
        if: contains(join(github.event.issue.labels.*.name, ','), 'originaltime-')
        # if: contains(github.event.issue.labels.*.name, 'originaltime-') # TODO: fix this label filter # it's not working because labels returns an arr of obj
        env: 
          LABELS: ${{ toJson(github.event.issue.labels) }}
        run: node ./roiScript/send-time.mjs
