name: Measure issue timestamp

on:
  issues: 
    types: [assigned]

jobs:
  record_issue_timestamp:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3

      # TODO: figure out how to track this issue branch in the next pr workflow 
      # 1 - create branch linked to the issue 
      - name: Create branch linked to the issue 
        id: create_branch
        run: |
          issue_number=$(echo "${{ github.event.issue.number }}")
          git checkout -b "issue-${issue_number}"
          echo "::set-output name=issue_branch::issue-${issue_number}"

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.create_branch.outputs.issue_branch }}
    
      - name: Add Issue Timestamp To File
        working-directory: roiScript
        run: | 
           timestamp=$(date +"%Y-%m-%d %H:%M:%S")
           echo "Timestamp: $timestamp" >> issue_timestamp.log

      - name: Commit Issue Timestamp # without specifying the username in the commit the commit will be done by the user 
        run: | 
          git config --global user.email "Polinka7max@gmail.com"
          git config --global user.name "Dunridge"
          git add .
          git commit -m "Add issue timestamp by $GITHUB_ACTOR"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

