name: Measure issue timestamp

on:
  issues: 
    types: [assigned]

jobs:
  record_issue_timestamp:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Get Current Timestamp for Issue
        id: issue_timestamp
        run: echo "::set-output name=issue_timestamp::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Upload Timestamp as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: issue-timestamp
          path: ${{ steps.issue_timestamp.outputs.issue_timestamp }}

  # TODO: write a step to send the data between the workflows -- https://stackoverflow.com/questions/60355925/share-artifacts-between-workflows-github-actions
  
