name: Measure issue timestamp

on:
  issues:
    types: [assigned]

jobs:
  record_issue_timestamp:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Create branch linked to the issue
        id: create_branch
        run: |
          issue_number=$(echo "${{ github.event.issue.number }}")
          git checkout -b "issue-${issue_number}"
          echo "::set-output name=issue_branch::issue-${issue_number}"

      # TODO: debug the issue with the created branc here (it should be check out but on the last step it returns to main)
      # - name: Checkout branch
      #   uses: actions/checkout@v2
      #   with:
      #     ref: ${{ steps.create_branch.outputs.issue_branch }}

      # TODO: try pulling in a separate step here

      - name: Add Issue Timestamp To File
        working-directory: roiScript
        run: |
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          echo "Timestamp: $timestamp" >> issue_timestamp.log

      # TODO: if mentioning it here won't work then pass the variable through the previous step
      # TODO: here add git checkout of the created branch
      # TODO: removed git pull ${{steps.create_branch.outputs.issue_branch}} because of an error
      # HEAD:${{ github.ref }}
      # don't need this: git checkout ${{steps.create_branch.outputs.issue_branch}}
      # temporarily removed git fetch origin ${{ steps.create_branch.outputs.issue_branch }}
      - name: Commit Issue Timestamp
        run: |
          git config --global user.email "Polinka7max@gmail.com"
          git config --global user.name "Dunridge"
          git pull origin ${{ steps.create_branch.outputs.issue_branch }}
          git add .
          git commit -m "Add issue timestamp by $GITHUB_ACTOR"
          git push --force-with-lease https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ steps.create_branch.outputs.issue_branch }}
