name: ROI pull request metrics

on:
  pull_request:
    types: [review_requested] # it triggers here and then in the js file the time is measured
  # test trigger that fires on change of the PR name 
  # issues:
  #   types: [assigned, unlabeled]
  # pull_request:
  #   types: [opened, edited]
  #   branches:
  #     - main 

jobs:
  metric:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18 # TODO: pick the node version that's compatible with libraries 

    # TODO: learn the path to node to run the script from the sh file
    - name: Print Node.js path
      run: which node

    # - name: Change directory # not needed since we specify the working directory for the npm install
    #   run: cd roiScript
      
    - name: Install
      run: npm install
      working-directory: ./roiScript

    - name: Log Pull Request Payload
      run: |
        pullRequestPayload=$(cat $GITHUB_EVENT_PATH)
        echo "Pull Request Payload: $pullRequestPayload"

    - name: Access PR Payload
      id: pr-payload
      run: |
        pullRequestPayload=$(cat $GITHUB_EVENT_PATH)
        echo "Pull Request Payload: $pullRequestPayload"
        echo "::set-output name=pr_payload::$pullRequestPayload"

    # TODO: pass these results to the script 
    - name: Run issue-metrics tool
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:ProgramEquity/amplify is:issue created:${{ env.last_month }} -reason:"not planned"'

    - name: Run
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PR_PAYLOAD: ${{ steps.pr-payload.outputs.pr_payload }}
      run: node ./roiScript/issue-metrics.mjs
      # run: node ./roiScript/issue-metrics.js
    # - name: Set execute permissions for run-metrics.sh
    #   run: chmod +x ./run-metrics.sh

    # - name: Set execute permissions
    #   run: chmod +x ./issue-metrics.js
      # run: chmod +x ${{ github.workspace }}/issue-metrics.js

    # - name: Issue Metrics
    #   uses: github/issue-metrics@v2
    #   with:
    #     entryPoint: ./run-metrics.sh # TODO: configure values passed to the config
        # entryPoint: ./issue-metrics.js # error: exec ./issue-metrics.js: exec format error
        # entryPoint: ${{ github.workspace }}/issue-metrics.js # error: docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/home/runner/work/amplify/amplify/issue-metrics.js": stat /home/runner/work/amplify/amplify/issue-metrics.js: no such file or directory: unknown.
        # args: '{"github-token": "${{ secrets.GH_TOKEN }}", "payload": ${{ toJson(github) }}}'  
