name: Spellcheck

on: [pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '14.x'

      - name: Spellcheck
        uses: lingeorge88/amplify-ghActions-tests/.github/workflows/spellcheck@main
        with:
          path: '.'

      - name: Post spellcheck results
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const context = github.context
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN)

            const results = fs.readFileSync('spellcheck-results.txt', 'utf8')
            const lines = results.split('\n')
            const misspelledWords = lines.slice(1, -2).map(line => line.trim())

            if (misspelledWords.length === 0) {
              console.log('No misspelled words found.')
              return
            }

            const body = `**Spellcheck Results:**

            ${misspelledWords.join('\n')}`

            try {
              await octokit.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body
              })
            } catch (error) {
              console.error('An error occurred:', error)
            }